# Generated by Django 5.2.4 on 2026-05-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_student_end_date_student_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(help_text='e.g. 2023-2024', max_length=20)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('model_exam_date', models.DateField(blank=True, null=True)),
                ('final_exam_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)'), ('A1 ONLINE', 'A1 (Online)'), ('A2 ONLINE', 'A2 (Online)'), ('B1 ONLINE', 'B1 (Online)'), ('B2 ONLINE', 'B2 (Online)'), ('ONLINE', 'Online'), ('A1 EXAM PREPERATION', 'A1 (Exam Preparation)'), ('A2 EXAM PREPERATION', 'A2 (Exam Preparation)'), ('B1 EXAM PREPERATION', 'B1 (Exam Preparation)'), ('B2 EXAM PREPERATION', 'B2 (Exam Preparation)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='trainers.academicbatch'),
        ),
    ]
