# Generated by Django 5.2.4 on 2026-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0009_academicbatch_alter_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicbatch',
            name='grade',
            field=models.CharField(blank=True, help_text='e.g. Grade 10', max_length=50, null=True),
        ),
    ]
