# Generated by Django 5.2.4 on 2026-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
