# Generated by Django 5.2.4 on 2026-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_dailyreportattachment_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='next_day_agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report_type',
            field=models.CharField(choices=[('MORNING', 'Morning Agenda'), ('EVENING', 'Evening Report')], db_index=True, default='EVENING', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
